spring.application.name=event-service
server.port=${EVENT_SERVICE_PORT:8083}

eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL}
eureka.client.register-with-eureka=${EUREKA_REGISTER_WITH_EUREKA}
eureka.client.fetch-registry=${EUREKA_FETCH_REGISTRY}
# Helps local/dev setups; safe to keep.
eureka.instance.prefer-ip-address=${EUREKA_PREFER_IP_ADDRESS}

jwt.secret=${JWT_SECRET}

spring.datasource.url=${EVENT_DB_URL}
spring.datasource.username=${EVENT_DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER}

spring.jpa.hibernate.ddl-auto=${EVENT_JPA_DDL_AUTO}
spring.jpa.database-platform=${JPA_DATABASE_PLATFORM}
spring.jpa.show-sql=${EVENT_JPA_SHOW_SQL}

spring.data.redis.host=${EVENT_REDIS_HOST}
spring.data.redis.port=${EVENT_REDIS_PORT}
spring.data.redis.username=${EVENT_REDIS_USERNAME}
spring.data.redis.password=${EVENT_REDIS_PASSWORD}

# -------- Kafka Broker --------
spring.kafka.bootstrap-servers=${EVENT_KAFKA_BOOTSTRAP_SERVERS}

# -------- Consumer --------
spring.kafka.consumer.group-id=${EVENT_KAFKA_CONSUMER_GROUP_ID}
spring.kafka.consumer.auto-offset-reset=${EVENT_KAFKA_CONSUMER_AUTO_OFFSET_RESET}

spring.kafka.consumer.key-deserializer=${KAFKA_CONSUMER_KEY_DESERIALIZER}
spring.kafka.consumer.value-deserializer=${KAFKA_CONSUMER_VALUE_DESERIALIZER}

spring.kafka.consumer.properties.spring.json.trusted.packages=${KAFKA_CONSUMER_JSON_TRUSTED_PACKAGES}
spring.kafka.consumer.properties.spring.json.use.type.headers=${KAFKA_CONSUMER_JSON_USE_TYPE_HEADERS}
spring.kafka.consumer.properties.spring.json.value.default.type=com.eventmate.event.dto.BookingEvent

# One-click security toggle (dev only): set false to disable security in this service
eventmate.security.enabled=${EVENT_SECURITY_ENABLED}
eventmate.internal.token=${INTERNAL_TOKEN}
