spring.application.name=event-service
server.port=8083

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
# Helps local/dev setups; safe to keep.
eureka.instance.prefer-ip-address=true

spring.datasource.url=jdbc:postgresql://localhost:5432/eventmate-event
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.data.redis.host=redis-13318.crce292.ap-south-1-2.ec2.cloud.redislabs.com
spring.data.redis.port=13318
spring.data.redis.username=default
spring.data.redis.password=${REDIS_PASSWORD}

# -------- Kafka Broker --------
spring.kafka.bootstrap-servers=localhost:9092

# -------- Consumer --------
spring.kafka.consumer.group-id=event-service
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.value.default.type=com.eventmate.event.dto.BookingEvent

# One-click security toggle (dev only): set false to disable security in this service
eventmate.security.enabled=true
