spring.application.name=eureka-server

server.port=${EUREKA_SERVER_PORT:8761}

eureka.client.register-with-eureka=${EUREKA_SERVER_REGISTER_WITH_EUREKA}
eureka.client.fetch-registry=${EUREKA_SERVER_FETCH_REGISTRY}
# Expose the canonical URL that clients should use.
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL}
